apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: team1
  namespace: naughty
spec:
  interval: 5s
  path: ./naughty
  prune: false
  serviceAccountName: team1
  sourceRef:
    kind: GitRepository
    name: team1
