apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: team1-app
  name: team1-app
  namespace: apps1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          # resources:
          #   limits:
          #     cpu: 0.5
